# Generated by Django 5.0.1 on 2024-03-07 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('rules', models.TextField()),
                ('publicity', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceName', models.TextField()),
                ('spaceColor', models.TextField(blank=True, null=True)),
                ('spaceType', models.TextField(blank=True, default='', null=True)),
                ('spaceValue', models.JSONField(blank=True, null=True)),
                ('spaceBoardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyType', models.TextField()),
                ('currencyImage', models.ImageField(blank=True, upload_to='public')),
                ('currencyBoardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='GameLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, null=True)),
                ('boardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.boardgame')),
            ],
        ),
    ]
