# Generated by Django 5.0.2 on 2024-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rules',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='boardgamespace',
            name='spaceDesc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currencyDesc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
