# Generated by Django 5.0.2 on 2024-03-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_userprofile_boardgame_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='profile',
        ),
    ]
