# Generated by Django 5.0.2 on 2024-03-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_boardgame_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
