# Generated by Django 5.0.2 on 2024-03-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgamespace',
            name='spaceImage',
        ),
        migrations.AlterField(
            model_name='boardgamespace',
            name='spaceColor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currencyImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
