# Generated by Django 5.0.2 on 2024-03-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_boardgamespace_spaceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamespace',
            name='spaceBoardID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currencyBoardID',
            field=models.IntegerField(),
        ),
    ]
