# Generated by Django 5.0.2 on 2024-03-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_boardgame_profile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
        ),
    ]
