# Generated by Django 4.1.7 on 2024-04-15 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_room_password_alter_room_name_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TextField()),
                ('itemImage', models.ImageField(blank=True, upload_to='')),
                ('itemPurpose', models.JSONField(blank=True, null=True)),
                ('itemType', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='playerMax',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='playerMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='winGoal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='winGoalType',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='item',
            name='itemBoardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.boardgame'),
        ),
    ]
