# Generated by Django 5.0.2 on 2024-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_boardgamespace_spacecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamespace',
            name='spaceColor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
