# Generated by Django 5.0.2 on 2024-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currencyImage',
            field=models.ImageField(blank=True, upload_to='public/images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='public/images'),
        ),
    ]
