# Generated by Django 5.0.1 on 2024-03-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_boardgamespace_spacecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamespace',
            name='spaceValue',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
