# Generated by Django 5.0.2 on 2024-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_currency_currencyimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currencyImage',
            field=models.ImageField(blank=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='public'),
        ),
    ]
