# Generated by Django 5.0.6 on 2024-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='playerMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='playerMin',
            field=models.IntegerField(null=True),
        ),
    ]
