# Generated by Django 5.0.2 on 2024-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_currency_currencyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='diceRoll',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgamespace',
            name='spaceDesc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgamespace',
            name='spaceImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='currency',
            name='currencyDesc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
