# Generated by Django 5.0.1 on 2024-03-06 04:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_boardgamespace_spacevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currencyImage',
            field=models.ImageField(blank=True, upload_to='public'),
        ),
        migrations.CreateModel(
            name='GameLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('boardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.boardgame')),
            ],
        ),
    ]
